import { useRef, useState } from "react";
import { api, money } from "../lib/api";

const TOTAL_REQUESTS = 4000;
const CONCURRENCY = 25;
const REQUEST_GAP_MS = 750;
const PRODUCT_IDS = ["prod_c2", "prod_e1", "prod_e2", "prod_b1", "prod_h1", "prod_s1"];

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

export default function SlowTraffic() {
  const [running, setRunning] = useState(false);
  const [processed, setProcessed] = useState(0);
  const [errors, setErrors] = useState(0);
  const [ordersPlaced, setOrdersPlaced] = useState(0);
  const [revenueCents, setRevenueCents] = useState(0);
  const [signups, setSignups] = useState(0);
  const [status, setStatus] = useState("");
  const cancelledRef = useRef(false);

  const pct = Math.round((processed / TOTAL_REQUESTS) * 100);

  async function start() {
    cancelledRef.current = false;
    setRunning(true);
    setProcessed(0);
    setErrors(0);
    setOrdersPlaced(0);
    setRevenueCents(0);
    setSignups(0);
    setStatus(`Launching ${TOTAL_REQUESTS.toLocaleString()} slow real endpoint requests...`);

    const startedAt = Date.now();
    let nextIndex = 0;
    let completed = 0;
    let failed = 0;
    let orderCount = 0;
    let revenue = 0;
    let signupCount = 0;
    const createdOrderIds = [];
    const createdTicketIds = [];
    const createdCredentials = [];

    function completeRequest({ failedRequest = false, orderTotalCents = 0, signup = false } = {}) {
      completed += 1;
      if (failedRequest) {
        failed += 1;
        setErrors(failed);
      }
      if (orderTotalCents) {
        orderCount += 1;
        revenue += orderTotalCents;
        setOrdersPlaced(orderCount);
        setRevenueCents(revenue);
      }
      if (signup) {
        signupCount += 1;
        setSignups(signupCount);
      }
      setProcessed(completed);
    }

    async function runEndpoint(index) {
      const productId = PRODUCT_IDS[index % PRODUCT_IDS.length];
      const bucket = index % 24;

      if (bucket === 0) return api.products({ limit: 12, page: (index % 3) + 1 });
      if (bucket === 1) return api.products({ q: "wireless", limit: 6 });
      if (bucket === 2) return api.featuredProducts();
      if (bucket === 3) return api.product(productId);
      if (bucket === 4) return api.cart();
      if (bucket === 5) return api.addToCart(productId, 1);
      if (bucket === 6) return api.updateCartItem(productId, 2);
      if (bucket === 7) return api.removeCartItem(productId);
      if (bucket === 8) return api.clearCart();
      if (bucket === 9) return api.orders();
      if (bucket === 10) {
        const order = await api.createOrder({
          shippingAddress: {
            line1: "1 Slow Traffic",
            city: "Austin",
            state: "TX",
            zip: "78701",
            country: "US",
          },
          paymentMethod: { type: "card", last4: "4242" },
        });
        if (order.order?.id) createdOrderIds.push(order.order.id);
        return { orderTotalCents: order.order?.totalCents || 0 };
      }
      if (bucket === 11) {
        const orderId = createdOrderIds[index % Math.max(createdOrderIds.length, 1)];
        return orderId ? api.order(orderId) : api.orders();
      }
      if (bucket === 12) {
        const orderId = createdOrderIds[index % Math.max(createdOrderIds.length, 1)];
        return orderId ? api.cancelOrder(orderId) : api.updateProfile({ phone: `555-${String(index).padStart(4, "0")}` });
      }
      if (bucket === 13) return api.tickets();
      if (bucket === 14) {
        const ticket = await api.createTicket({
          subject: `Slow traffic ticket ${index}`,
          body: "Generated by slow frontend traffic.",
          category: "product",
        });
        if (ticket.ticket?.id) createdTicketIds.push(ticket.ticket.id);
        return ticket;
      }
      if (bucket === 15) {
        const ticketId = createdTicketIds[index % Math.max(createdTicketIds.length, 1)];
        return ticketId ? api.ticket(ticketId) : api.tickets();
      }
      if (bucket === 16) {
        const ticketId = createdTicketIds[index % Math.max(createdTicketIds.length, 1)];
        return ticketId
          ? api.replyTicket(ticketId, "Slow traffic follow-up.")
          : api.createTicket({ subject: `Slow fallback ${index}`, body: "Generated by slow frontend traffic.", category: "other" });
      }
      if (bucket === 17) {
        const ticketId = createdTicketIds[index % Math.max(createdTicketIds.length, 1)];
        return ticketId ? api.closeTicket(ticketId) : api.updateProfile({ lastName: `Slow${index}` });
      }
      if (bucket === 18) return api.profile();
      if (bucket === 19) return api.updateProfile({ phone: `555-${String(index).padStart(4, "0")}` });
      if (bucket === 20) return api.returns();
      if (bucket === 21) return api.me();
      if (bucket === 22) {
        const suffix = `${Date.now()}_${index}`;
        const email = `slow_${suffix}@shopstorm.test`;
        const password = "Password1!";
        await api.signup({
          email,
          username: `slow_${suffix}`,
          password,
          firstName: "Slow",
          lastName: "Traffic",
        });
        createdCredentials.push({ email, password });
        return { signup: true };
      }

      const creds = createdCredentials[index % Math.max(createdCredentials.length, 1)];
      return creds ? api.login({ email: creds.email, password: creds.password }) : api.me();
    }

    try {
      await api.startSimulation(TOTAL_REQUESTS);

      async function worker(workerIndex) {
        await sleep(workerIndex * 100);
        while (!cancelledRef.current && nextIndex < TOTAL_REQUESTS) {
          const index = nextIndex;
          nextIndex += 1;
          await sleep(REQUEST_GAP_MS);

          try {
            const result = await runEndpoint(index);
            completeRequest({
              orderTotalCents: result?.orderTotalCents || 0,
              signup: !!result?.signup,
            });
          } catch {
            completeRequest({ failedRequest: true });
          }
        }
      }

      await Promise.all(Array.from({ length: CONCURRENCY }, (_, index) => worker(index)));

      await api.stopSimulation({
        metrics: {
          activeUsers: 0,
          totalPageViews: completed,
          ordersPlaced: orderCount,
          revenueCents: revenue,
          cartAbandons: 0,
          newSignups: signupCount,
          errorCount: failed,
        },
        progress: {
          processed: completed,
          total: TOTAL_REQUESTS,
          pct: Math.round((completed / TOTAL_REQUESTS) * 100),
        },
      });

      if (!cancelledRef.current) {
        setStatus(
          `Complete: ${completed.toLocaleString()} slow real endpoint requests in ${Date.now() - startedAt}ms`,
        );
      }
    } catch (err) {
      setStatus(`Error: ${err.message}`);
    } finally {
      setRunning(false);
    }
  }

  async function stop() {
    cancelledRef.current = true;
    setRunning(false);
    setStatus("Stopping slow traffic...");
    await api.stopSimulation({
      metrics: {
        activeUsers: 0,
        totalPageViews: processed,
        ordersPlaced,
        revenueCents,
        cartAbandons: 0,
        newSignups: signups,
        errorCount: errors,
      },
      progress: { processed, total: TOTAL_REQUESTS, pct },
    }).catch(() => {});
  }

  return (
    <div className="admin-page">
      <div className="admin-header">
        <div>
          <h1>Slow Traffic</h1>
          <p>Send 4,000 delayed frontend requests across all app endpoints.</p>
        </div>
      </div>

      {status && <div className="status-banner">{status}</div>}

      <div className="launch-section">
        <h2>Slow Real Endpoint Run</h2>
        <p>
          Requests are spread across product, cart, order, support, profile, auth, return, PUT, POST, GET, and DELETE routes.
          Up to {CONCURRENCY} workers run in parallel, with a {REQUEST_GAP_MS}ms gap per worker.
        </p>
        <div className="launch-btns">
          <button className="launch-btn launch-5k" onClick={start} disabled={running}>
            <span className="launch-num">4K</span>
            <span className="launch-label">Slow Real API</span>
            <span className="launch-sub">{CONCURRENCY} parallel</span>
          </button>
        </div>
        {running && (
          <button className="btn btn-danger" onClick={stop}>
            Stop Slow Traffic
          </button>
        )}
      </div>

      {(running || processed > 0) && (
        <div className="progress-section">
          <div className="progress-label">
            <span>
              Processing {processed.toLocaleString()} / {TOTAL_REQUESTS.toLocaleString()} requests
            </span>
            <span>{pct}%</span>
          </div>
          <div className="progress-bar">
            <div className="progress-fill" style={{ width: `${pct}%` }} />
          </div>
        </div>
      )}

      <div className="metrics-grid">
        <div className="metric-card metric-blue">
          <div className="metric-icon">⏳</div>
          <div className="metric-value">{running ? CONCURRENCY : 0}</div>
          <div className="metric-label">Parallel Workers</div>
        </div>
        <div className="metric-card metric-green">
          <div className="metric-icon">✓</div>
          <div className="metric-value">{processed.toLocaleString()}</div>
          <div className="metric-label">Completed</div>
        </div>
        <div className="metric-card metric-red">
          <div className="metric-icon">!</div>
          <div className="metric-value">{errors.toLocaleString()}</div>
          <div className="metric-label">Errors</div>
        </div>
        <div className="metric-card metric-gold">
          <div className="metric-icon">$</div>
          <div className="metric-value">{money(revenueCents)}</div>
          <div className="metric-label">Revenue</div>
        </div>
        <div className="metric-card metric-cyan">
          <div className="metric-icon">+</div>
          <div className="metric-value">{signups.toLocaleString()}</div>
          <div className="metric-label">Signups</div>
        </div>
      </div>
    </div>
  );
}
